version: "3.8"
services:
    db:
        build: ./db
        environment:
            POSTGRES_DB: guestbook
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data
    backend:
        build: ./backend
        environment:
            POSTGRES_DB: guestbook
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_HOST: db
        ports:
            - "4000:4000"
        depends_on:
            - db
    frontend:
        build: ./frontend
        ports:
            - "3000:80"
        depends_on:
            - backend
volumes:
    db_data:
